#!/bin/bash

##########################
#                        #
# ### README - PT_BR ### #
#                        #
################################################################################
#                                                                              #
#                                                                              #
# themepack2background v3.0 - Conversão de arquivos de tema do Windows         #
# themepack e deskthemepack para pacotes do Linux deb, rpm e txz.              #
#                                                                              #
# By Mauricio Ferrari                                                          #
#                                                                              #
#                                                                              #
# Descrição:                                                                   #
#                                                                              #
# Esse software tem como objetivo de reutilizar os arquivos de tema do Windows #
# themepack do descontinuado Windows 7, para transformá-los em pacotes úteis   #
# de instalação de Wallpapers para o Linux.                                    #
#                                                                              #
# Os pacotes deskthemepack do Windows 8, 8.1 e 10, por ter a mesmo formato de  #
# compactação "cab" e por ter sua estrutura similar, também poderão ser        #
# convertidos em pacotes para serem instalados no Linux.                       #
#                                                                              #
#                                                                              #
# Todos os Recursos:                                                           #
#                                                                              #
# themepack2background - Extrai as imagens dos pacotes (desk)themepack e       #
#                        instala as imagens diretamente nos diretórios dos     # 
#                        backgrounds das interfaces DDE, GNOME, KDE, MATE      #
#                        e XFCE.                                               #
#                                                                              #
# themepack2deb - Converte pacotes (desk)themepack em pacotes deb.             # 
# themepack2rpm - Converte pacotes (desk)themepack em pacotes rpm.             # 
# themepack2txz - Converte pacotes (desk)themepack em pacotes txz.             #
#                                                                              #
# Sintaxe:                                                                     #
#                                                                              #
# themepack2background package.themepack                                       #
# themepack2deb package.themepack                                              #
# themepack2rpm package.themepack                                              #
# themepack2txz package.themepack                                              #
#                                                                              #
# Parâmetros:                                                                  #
#                                                                              #
#    --default       : Suporte ao KDE e o XFCE por padrão.                     #
#                                                                              #  
#    --enable-dde    : Habilitar suporte ao DDE.                               #
#    --enable-mate   : Habilitar suporte ao MATE.                              #
#    --enable-gnome  : Habilitar suporte ao GNOME.                             #
#                                                                              #
#    --disable-dde   : Desabilitar suporte ao DDE.                             #
#    --disable-mate  : Desabilitar suporte ao MATE.                            #
#    --disable-gnome : Desabilitar suporte ao GNOME.                           #
#                                                                              #
#                                                                              #
#                            ### Copyright 2021 ###                            #
#                                                                              #
#                                                                              #
################################################################################

##########################
#                        #
# ### README - EN_US ### #
#                        #
################################################################################
#                                                                              #
#                                                                              #
# themepack2background v3.0 - Conversion of Windows theme files themepack      #
# and deskthemepack for Linux packages deb, rpm e txz.                         #
#                                                                              #
# By Mauricio Ferrari                                                          #
#                                                                              #
#                                                                              #
# Description:                                                                 #
#                                                                              #
# This software has as objective reuse Windows theme files themepack of        #
# discontinued Windows 7, to transform them into useful wallpaper              #
# installation packages for Linux.                                             #
#                                                                              #
# The packages deskthemepack of the Windows 8, 8.1 e 10, for having the same   #
# compression format "cab" and for having a similar structure, also may be     #
# converted into packages to be installed on Linux.                            #
#                                                                              #
#                                                                              #
# All Resources:                                                               #
#                                                                              #
# themepack2background - Extracts the images from packages (desk)themepack     #
#                        and install the images directly in the background     # 
#                        directories of the DDE, GNOME, KDE, MATE and XFCE     #
#                        interfaces.                                           #
#                                                                              #
# themepack2deb - Convert packages (desk)themepack in packages deb.            # 
# themepack2rpm - Convert packages (desk)themepack in packages rpm.            # 
# themepack2txz - Convert packages (desk)themepack in packages txz.            #
#                                                                              #
# Sintax:                                                                      #
#                                                                              #
# themepack2background package.themepack                                       #
# themepack2deb package.themepack                                              #
# themepack2rpm package.themepack                                              #
# themepack2txz package.themepack                                              #
#                                                                              #
# Parameters:                                                                  #
#                                                                              #
#    --default       : KDE and XFCE support by default.                        #
#                                                                              #  
#    --enable-dde    : Enable DDE support.                                     #
#    --enable-mate   : Enable MATE support.                                    #
#    --enable-gnome  : Enable GNOME support.                                   #
#                                                                              #
#    --disable-dde   : Disable DDE support.                                    #
#    --disable-mate  : Disable MATE support.                                   #
#    --disable-gnome : Disable GNOME support.                                  #
#                                                                              #
#                                                                              #
#                            ### Copyright 2021 ###                            #
#                                                                              #
#                                                                              #
################################################################################

DDE=enable
MATE=enable
GNOME=enable

define_defaut()
{
	DDE=disable
	MATE=disable
	GNOME=disable
}

fail_root()
{
	echo -e "\n The $( basename $0 ) resource requires administrative privileges! \n"; exit 1
}

info_view()
{
	head -122 $( basename $0 ) | sed "1d"; exit 0
}

define_name()
{
	cd $PKG/usr/share/xfce4/backdrops
	for OLDNAME in `ls -1`; do
		mv $OLDNAME $NAME-$OLDNAME
	done
}

dde_wall()
{
	mkdir -p /usr/share/wallpapers/deepin
	cd /usr/share/wallpapers/deepin
	ls -1 /usr/share/xfce4/backdrops/$NAME*.* | while read file; do
		ln -s "$file" .
	done
}

gnome_wall()
{
	mkdir -p $PKG/usr/share/backgrounds/gnome/$NAME
	cd $PKG/usr/share/backgrounds/gnome/$NAME
	ls -1 ../../../xfce4/backdrops/*.* | while read file; do
		ln -s "$file" .
	done
	mkdir -p $PKG/usr/share/gnome-background-properties
	cat << EOF > $PKG/usr/share/gnome-background-properties/gnome-$NAME.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE wallpapers SYSTEM "gnome-wp-list.dtd">
<wallpapers>
EOF
	ls -1 *.* | while read file; do
	cat << EOF >> $PKG/usr/share/gnome-background-properties/gnome-$NAME.xml
  <wallpaper deleted="false">
    <name>$file</name>
    <filename>/usr/share/backgrounds/gnome/$NAME/$file</filename>
    <pcolor>#27587E</pcolor>
    <scolor>#627F5A</scolor>
    <options>zoom</options>
  </wallpaper>
EOF
	done
	cat << EOF >> $PKG/usr/share/gnome-background-properties/gnome-$NAME.xml
</wallpapers>
EOF
}

mate_wall()
{
	mkdir -p /usr/share/backgrounds/mate/$NAME
	cd /usr/share/backgrounds/mate/$NAME
	ls -1 /usr/share/xfce4/backdrops/$NAME*.* | while read file; do
		ln -s "$file" .
	done
	mkdir -p /usr/share/mate-background-properties
	cat << EOF > /usr/share/mate-background-properties/mate-$NAME.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE wallpapers SYSTEM "mate-wp-list.dtd">
<wallpapers>
EOF
	ls -1 *.* | while read file; do
	cat << EOF >> /usr/share/mate-background-properties/mate-$NAME.xml
  <wallpaper deleted="false">
    <name>$file</name>
    <filename>/usr/share/backgrounds/mate/$NAME/$file</filename>
    <pcolor>#27587E</pcolor>
    <scolor>#627F5A</scolor>
    <options>zoom</options>
  </wallpaper>
EOF
	done
	cat << EOF >> /usr/share/mate-background-properties/mate-$NAME.xml
</wallpapers>
EOF
}

kde_wall()
{
	cd /usr/share/wallpapers
	ls -1 /usr/share/xfce4/backdrops/$NAME*.* | while read file; do
		ln -s "$file" .
	done
}

xfce_wall()
{
	cd /usr/share/backgrounds/xfce
	ls -1 /usr/share/xfce4/backdrops/$NAME*.* | while read file; do
		ln -s "$file" .
	done
}

[ "$1" == ""  ] && info_view
[ "$UID" != 0 ] && fail_root

PARM=$( echo $* | sed "s/ /&\n/g" | grep "\-\-"    )
LIST=$( echo $* | sed "s/ /&\n/g" | grep -v "\-\-" )

for OPTION in $PARM; do
	[ "$OPTION" == "--default"       ] && define_defaut
	[ "$OPTION" == "--enable-dde"    ] && DDE=enable
	[ "$OPTION" == "--enable-mate"   ] && MATE=enable
	[ "$OPTION" == "--enable-gnome"  ] && GNOME=enable
	[ "$OPTION" == "--disable-dde"   ] && DDE=disable
	[ "$OPTION" == "--disable-mate"  ] && MATE=disable
	[ "$OPTION" == "--disable-gnome" ] && GNOME=disable
done

for FILE in $LIST ; do
	NAME=$( basename $FILE | cut -d '.' -f1 )
	TMP=/tmp/$NAME
	mkdir -p $TMP
	cabextract -d $TMP $FILE
	mv $TMP/D*/* /usr/share/xfce4/backdrops/
	define_name
	chown -R root:root /usr/share/xfce4/backdrops/$NAME*.*
	chmod 644 /usr/share/xfce4/backdrops/$NAME*.*
	[ "$DDE"  == "enable"  ] && dde_wall
	[ "$MATE" == "enable"  ] && mate_wall
	[ "$GNOME" == "enable" ] && gnome_wall
	kde_wall
	xfce_wall
	rm -rf $TMP $PKG
	cd $CWD
done
exit 0
