#!/bin/bash

## ### README - PT_BR ### ######################################################
#                                                                              #
# themepack2background v3.2 - Conversão de arquivos de tema do Windows         #
# themepack e deskthemepack para pacotes do Linux deb, rpm e txz.              #
#                                                                              #
# By Mauricio Ferrari                                                          #
#                                                                              #
#                                                                              #
# Descrição:                                                                   #
#                                                                              #
# Esse software tem como objetivo de reutilizar os arquivos de tema do Windows #
# themepack do descontinuado Windows 7, para transformá-los em pacotes úteis   #
# de instalação de Wallpapers para o Linux.                                    #
#                                                                              #
# Os pacotes deskthemepack do Windows 8, 8.1 e 10, por ter a mesmo formato de  #
# compactação "cab" e por ter sua estrutura similar, também poderão ser        #
# convertidos em pacotes para serem instalados no Linux.                       #
#                                                                              #
#                                                                              #
# Todos os Recursos:                                                           #
#                                                                              #
# themepack2background - Extrai as imagens dos pacotes (desk)themepack e       #
#                        instala as imagens diretamente nos diretórios dos     #
#                        backgrounds das interfaces DDE, GNOME, KDE, MATE      #
#                        e XFCE.                                               #
#                                                                              #
# themepack2deb - Converte pacotes (desk)themepack em pacotes deb.             #
# themepack2rpm - Converte pacotes (desk)themepack em pacotes rpm.             #
# themepack2txz - Converte pacotes (desk)themepack em pacotes txz.             #
#                                                                              #
# Sintaxe:                                                                     #
#                                                                              #
# themepack2background package.themepack                                       #
# themepack2deb package.themepack                                              #
# themepack2rpm package.themepack                                              #
# themepack2txz package.themepack                                              #
#                                                                              #
# Parâmetros:                                                                  #
#                                                                              #
#     --default       : Suporte ao KDE e o XFCE por padrão.                    #
#     --enable-dde    : Habilitar suporte ao DDE.                              #
#     --enable-mate   : Habilitar suporte ao MATE.                             #
#     --enable-gnome  : Habilitar suporte ao GNOME.                            #
#     --disable-dde   : Desabilitar suporte ao DDE.                            #
#     --disable-mate  : Desabilitar suporte ao MATE.                           #
#     --disable-gnome : Desabilitar suporte ao GNOME.                          #
#                                                                              #
# Todas as DEs estão ativadas por padrão.                                      #
#                                                                              #
############################ ### Copyleft 2021  ### ############################


## ### README - EN_US ### ######################################################
#                                                                              #
# themepack2background v3.2 - Conversion of Windows theme files themepack      #
# and deskthemepack for Linux packages deb, rpm e txz.                         #
#                                                                              #
# By Mauricio Ferrari                                                          #
#                                                                              #
#                                                                              #
# Description:                                                                 #
#                                                                              #
# This software has as objective reuse Windows theme files themepack of        #
# discontinued Windows 7, to transform them into useful wallpaper              #
# installation packages for Linux.                                             #
#                                                                              #
# The packages deskthemepack of the Windows 8, 8.1 e 10, for having the same   #
# compression format "cab" and for having a similar structure, also may be     #
# converted into packages to be installed on Linux.                            #
#                                                                              #
#                                                                              #
# All Resources:                                                               #
#                                                                              #
# themepack2background - Extracts the images from packages (desk)themepack     #
#                        and install the images directly in the background     # 
#                        directories of the DDE, GNOME, KDE, MATE and XFCE     #
#                        interfaces.                                           #
#                                                                              #
# themepack2deb - Convert packages (desk)themepack in packages deb.            #
# themepack2rpm - Convert packages (desk)themepack in packages rpm.            #
# themepack2txz - Convert packages (desk)themepack in packages txz.            #
#                                                                              #
# Sintax:                                                                      #
#                                                                              #
# themepack2background package.themepack                                       #
# themepack2deb package.themepack                                              #
# themepack2rpm package.themepack                                              #
# themepack2txz package.themepack                                              #
#                                                                              #
# Parameters:                                                                  #
#                                                                              #
#     --default       : KDE and XFCE support by default.                       #
#     --enable-dde    : Enable DDE support.                                    #
#     --enable-mate   : Enable MATE support.                                   #
#     --enable-gnome  : Enable GNOME support.                                  #
#     --disable-dde   : Disable DDE support.                                   #
#     --disable-mate  : Disable MATE support.                                  #
#     --disable-gnome : Disable GNOME support.                                 #
#                                                                              #
# All DEs are enabled by default.                                              #
#                                                                              #
############################ ### Copyleft 2021  ### ############################


# ### Default values. ###

DDE=enable
MATE=enable
GNOME=enable


# ### Info function. ###

info_view() 
{
	: "$( head -105 $0 )"; : "${_//\# /}"; : "${_/!\/bin\/bash/}"; echo -e "${_//\#/}\n"
	exit 0
}


# ### Add package name in the names for image files. ###

define_name()
{
	cd $tmp/DesktopBackground
	for oldname in *; do
		mv $oldname $name-$oldname
	done
}


# ### Gnome support. ###

gnome_wall()
{
	mkdir -p /usr/share/backgrounds/gnome/$name
	cd /usr/share/backgrounds/gnome/$name

	for img in ../../../xfce4/backdrops/$name*; do
		ln -s "$img" .
	done

	mkdir -p /usr/share/gnome-background-properties
echo '<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE wallpapers SYSTEM "gnome-wp-list.dtd">
<wallpapers>' > /usr/share/gnome-background-properties/gnome-$name.xml

	for img in *; do
	echo "  <wallpaper deleted=\"false\">
    <name>$img</name>
    <filename>/usr/share/backgrounds/gnome/$name/$img</filename>
    <pcolor>#27587E</pcolor>
    <scolor>#627F5A</scolor>
    <options>zoom</options>
  </wallpaper>" >> /usr/share/gnome-background-properties/gnome-$name.xml
	done

	echo '</wallpapers>' >> /usr/share/gnome-background-properties/gnome-$name.xml
}


# ### Mate support. ###

mate_wall()
{
	mkdir -p /usr/share/backgrounds/mate/$name
	cd /usr/share/backgrounds/mate/$name

	for img in ../../../xfce4/backdrops/$name*; do
		ln -s "$img" .
	done

	mkdir -p /usr/share/mate-background-properties
	echo '<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE wallpapers SYSTEM "mate-wp-list.dtd">
<wallpapers>' > /usr/share/mate-background-properties/mate-$name.xml

	for img in *; do
	echo "    <wallpaper deleted=\"false\">
    <name>$img</name>
    <filename>/usr/share/backgrounds/mate/$name/$img</filename>
    <pcolor>#27587E</pcolor>
    <scolor>#627F5A</scolor>
    <options>zoom</options>
  </wallpaper>" >> /usr/share/mate-background-properties/mate-$name.xml
	done

	echo '</wallpapers>' >> /usr/share/mate-background-properties/mate-$name.xml
}


# ### KDE and DDE support. ###

kde_wall()
{

	kdedir=/usr/share/wallpapers

	[ "$DDE" == "enable" ] && {
		kdedir+=/deepin
		bdir=../
		mkdir -p $kdedir
	}

	cd $kdedir
	for img in $bdir../xfce4/backdrops/$name*; do
		ln -s "$img" .
	done
}


# ### XFCE support. ###

xfce_wall()
{
	cd /usr/share/backgrounds/xfce
	for img in ../../xfce4/backdrops/$name*; do
		ln -s "$img" .
	done
}


# ### Function for parameters and arguments mapping. ###

for parms in $@; do

	# ### Detect parameters. ###

	case "$parms" in

		--default)  DDE=disable
					MATE=disable
					GNOME=disable ;;

		--enable-dde) DDE=enable ;;
		--enable-mate) MATE=enable ;;
		--enable-gnome) GNOME=enable ;;
		--disable-dde) DDE=disable ;;
		--disable-mate) MATE=disable ;;
		--disable-gnome) GNOME=disable ;;
		-h|--help) info_view ;;
	esac

	# ### Detect arguments. ###

	case "$parms" in
		--*) ;;
		  *) args+=" $parms"
	esac
done


# ### Control messages. ###

[ ! "$args" ] && info_view

[ "$UID" != 0 ] && {
	echo -e "\n\e[31mThe ${0##*/} resouce requires administrative privileges!\e[m\n" >&2
	exit 1
}


# ### Conversion step. ###

for file in $args; do

	# ### Message for file not found. ###

	[ ! -e $file ] && {
		echo -e "\n\e[31mThe \"$file\" file was not found!\e[m\n" >&2
		continue
	}

	: "${file##*/}"; name="${_%%.*}"
	tmp=/tmp/$name
	default_dir=/usr/share/xfce4/backdrops/
	mkdir -p $tmp
	cabextract -d $tmp $file
	
	# ### Message for invalid file. ###

	[ "$?" != 0 ] && {
		echo -e "\n\e[31mThe \"$file\" file is invalid!\e[m\n" >&2
		rm -rf $tmp
		continue
	}
	
	define_name
	mv $tmp/DesktopBackground/* $default_dir
	chown -R root:root /usr/share/xfce4/backdrops/$name*.*
	chmod 644 /usr/share/xfce4/backdrops/$name*.*
	[ "$MATE" == "enable"  ] && mate_wall
	[ "$GNOME" == "enable" ] && gnome_wall
	kde_wall
	xfce_wall
	rm -rf $tmp
	cd $cwd
done

exit 0
