#!/bin/bash

##########################
#                        #
# ### README - PT_BR ### #
#                        #
################################################################################
#                                                                              #
#                                                                              #
# themepack2background v3.0 - Conversão de arquivos de tema do Windows         #
# themepack e deskthemepack para pacotes do Linux deb, rpm e txz.              #
#                                                                              #
# By Mauricio Ferrari                                                          #
#                                                                              #
#                                                                              #
# Descrição:                                                                   #
#                                                                              #
# Esse software tem como objetivo de reutilizar os arquivos de tema do Windows #
# themepack do descontinuado Windows 7, para transformá-los em pacotes úteis   #
# de instalação de Wallpapers para o Linux.                                    #
#                                                                              #
# Os pacotes deskthemepack do Windows 8, 8.1 e 10, por ter a mesmo formato de  #
# compactação "cab" e por ter sua estrutura similar, também poderão ser        #
# convertidos em pacotes para serem instalados no Linux.                       #
#                                                                              #
#                                                                              #
# Todos os Recursos:                                                           #
#                                                                              #
# themepack2background - Extrai as imagens dos pacotes (desk)themepack e       #
#                        instala as imagens diretamente nos diretórios dos     # 
#                        backgrounds das interfaces DDE, GNOME, KDE, MATE      #
#                        e XFCE.                                               #
#                                                                              #
# themepack2deb - Converte pacotes (desk)themepack em pacotes deb.             # 
# themepack2rpm - Converte pacotes (desk)themepack em pacotes rpm.             # 
# themepack2txz - Converte pacotes (desk)themepack em pacotes txz.             #
#                                                                              #
# Sintaxe:                                                                     #
#                                                                              #
# themepack2background package.themepack                                       #
# themepack2deb package.themepack                                              #
# themepack2rpm package.themepack                                              #
# themepack2txz package.themepack                                              #
#                                                                              #
# Parâmetros:                                                                  #
#                                                                              #
#    --default       : Suporte ao KDE e o XFCE por padrão.                     #
#                                                                              #  
#    --enable-dde    : Habilitar suporte ao DDE.                               #
#    --enable-mate   : Habilitar suporte ao MATE.                              #
#    --enable-gnome  : Habilitar suporte ao GNOME.                             #
#                                                                              #
#    --disable-dde   : Desabilitar suporte ao DDE.                             #
#    --disable-mate  : Desabilitar suporte ao MATE.                            #
#    --disable-gnome : Desabilitar suporte ao GNOME.                           #
#                                                                              #
#                                                                              #
#                            ### Copyright 2021 ###                            #
#                                                                              #
#                                                                              #
################################################################################

##########################
#                        #
# ### README - EN_US ### #
#                        #
################################################################################
#                                                                              #
#                                                                              #
# themepack2background v3.0 - Conversion of Windows theme files themepack      #
# and deskthemepack for Linux packages deb, rpm e txz.                         #
#                                                                              #
# By Mauricio Ferrari                                                          #
#                                                                              #
#                                                                              #
# Description:                                                                 #
#                                                                              #
# This software has as objective reuse Windows theme files themepack of        #
# discontinued Windows 7, to transform them into useful wallpaper              #
# installation packages for Linux.                                             #
#                                                                              #
# The packages deskthemepack of the Windows 8, 8.1 e 10, for having the same   #
# compression format "cab" and for having a similar structure, also may be     #
# converted into packages to be installed on Linux.                            #
#                                                                              #
#                                                                              #
# All Resources:                                                               #
#                                                                              #
# themepack2background - Extracts the images from packages (desk)themepack     #
#                        and install the images directly in the background     # 
#                        directories of the DDE, GNOME, KDE, MATE and XFCE     #
#                        interfaces.                                           #
#                                                                              #
# themepack2deb - Convert packages (desk)themepack in packages deb.            # 
# themepack2rpm - Convert packages (desk)themepack in packages rpm.            # 
# themepack2txz - Convert packages (desk)themepack in packages txz.            #
#                                                                              #
# Sintax:                                                                      #
#                                                                              #
# themepack2background package.themepack                                       #
# themepack2deb package.themepack                                              #
# themepack2rpm package.themepack                                              #
# themepack2txz package.themepack                                              #
#                                                                              #
# Parameters:                                                                  #
#                                                                              #
#    --default       : KDE and XFCE support by default.                        #
#                                                                              #  
#    --enable-dde    : Enable DDE support.                                     #
#    --enable-mate   : Enable MATE support.                                    #
#    --enable-gnome  : Enable GNOME support.                                   #
#                                                                              #
#    --disable-dde   : Disable DDE support.                                    #
#    --disable-mate  : Disable MATE support.                                   #
#    --disable-gnome : Disable GNOME support.                                  #
#                                                                              #
#                                                                              #
#                            ### Copyright 2021 ###                            #
#                                                                              #
#                                                                              #
################################################################################

CWD=$PWD
ARCH=${ARCH:-noarch}
VERSION=${VERSION:-1.0}
RELEASE=${RELEASE:-1}

DDE=enable
MATE=enable
GNOME=enable

define_defaut()
{
	DDE=disable
	MATE=disable
	GNOME=disable
}

DISTRO=$( neofetch | grep OS | cut -d" " -f2 )
[ "$DISTRO" == "" ] && DISTRO=$( grep ^NAME /etc/os-release | cut -d"=" -f2 )
[ "$DISTRO" == "" ] && DISTRO=$( uname -s )

fail_root()
{
	echo -e "\n The $( basename $0 ) resource requires administrative privileges! \n"; exit 1
}

info_view()
{
	head -122 $( basename $0 ) | sed "1d"; exit 0
}

define_name()
{
	cd $PKG/usr/share/xfce4/backdrops
	for OLDNAME in `ls -1`; do
		mv $OLDNAME $NAME-$OLDNAME
	done
}

spec_gen()
{
echo "Summary: Package gererated from $FILE, by $( basename $0 ).
Name: $NAME-wall
Version: $VERSION
Release: $RELEASE
License: GPL
BuildArch: $ARCH
BuildRoot: $NPG

%description

Package created in $DISTRO. Gererated from $FILE, by $( basename $0 ).

%prep

echo “BUILDROOT = \$RPM_BUILD_ROOT“
mkdir -p \$RPM_BUILD_ROOT
cp -r $PKG/usr \$RPM_BUILD_ROOT
exit

%files

%attr(0644, root, root) /usr/share/xfce4/backdrops/*
/usr/share/backgrounds/xfce/
/usr/share/wallpapers/" | tee -a $NPG/SPECS/$NAME-$VERSION.spec > /dev/null

[ "$DDE" == "enable" ] && echo "/usr/share/wallpapers/deepin/" | tee -a $NPG/SPECS/$NAME-$VERSION.spec > /dev/null

[ "$MATE" == "enable" ] && echo "/usr/share/mate-background-properties/
/usr/share/backgrounds/mate/$NAME/" | tee -a $NPG/SPECS/$NAME-$VERSION.spec > /dev/null

[ "$GNOME" == "enable" ] && echo "/usr/share/gnome-background-properties/
/usr/share/backgrounds/gnome/$NAME/
" | tee -a $NPG/SPECS/$NAME-$VERSION.spec > /dev/null

echo "%post

cd /usr/share/wallpapers
ls -1 /usr/share/xfce4/backdrops/$NAME*.* | while read file; do
	ln -s \"\$file\" .
done

cd /usr/share/backgrounds/xfce
ls -1 /usr/share/xfce4/backdrops/$NAME*.* | while read file; do
	ln -s \"\$file\" .
done
" | tee -a $NPG/SPECS/$NAME-$VERSION.spec > /dev/null

[ "$DDE" == "enable" ] && echo "cd /usr/share/wallpapers/deepin
ls -1 /usr/share/xfce4/backdrops/$NAME*.* | while read file; do
	ln -s \"\$file\" .
done
" | tee -a $NPG/SPECS/$NAME-$VERSION.spec > /dev/null

[ "$GNOME" == "enable" ] && echo "cd /usr/share/backgrounds/gnome/$NAME
ls -1 /usr/share/xfce4/backdrops/$NAME*.* | while read file; do
	ln -s \"\$file\" .
done
cat << EOF > /usr/share/gnome-background-properties/gnome-$NAME.xml
<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<!DOCTYPE wallpapers SYSTEM \"gnome-wp-list.dtd\">
<wallpapers>
EOF
ls -1 *.* | while read file; do
cat << EOF >> /usr/share/gnome-background-properties/gnome-$NAME.xml
  <wallpaper deleted=\"false\">
    <name>\$file</name>
    <filename>/usr/share/backgrounds/gnome/$NAME/\$file</filename>
    <pcolor>#27587E</pcolor>
    <scolor>#627F5A</scolor>
    <options>zoom</options>
  </wallpaper>
EOF
done
cat << EOF >> /usr/share/gnome-background-properties/gnome-$NAME.xml
</wallpapers>
EOF
" | tee -a $NPG/SPECS/$NAME-$VERSION.spec > /dev/null

[ "$MATE" == "enable" ] && echo "cd /usr/share/backgrounds/mate/$NAME
ls -1 /usr/share/xfce4/backdrops/$NAME*.* | while read file; do
	ln -s \"\$file\" .
done
cat << EOF > /usr/share/mate-background-properties/mate-$NAME.xml
<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<!DOCTYPE wallpapers SYSTEM \"mate-wp-list.dtd\">
<wallpapers>
EOF
ls -1 *.* | while read file; do
cat << EOF >> /usr/share/mate-background-properties/mate-$NAME.xml
  <wallpaper deleted=\"false\">
    <name>\$file</name>
    <filename>/usr/share/backgrounds/mate/$NAME/\$file</filename>
    <pcolor>#27587E</pcolor>
    <scolor>#627F5A</scolor>
    <options>zoom</options>
  </wallpaper>
EOF
done
cat << EOF >> /usr/share/mate-background-properties/mate-$NAME.xml
</wallpapers>
EOF
" | tee -a $NPG/SPECS/$NAME-$VERSION.spec > /dev/null

echo "%postun

rm /usr/share/backgrounds/xfce/$NAME*
rm /usr/share/wallpapers/$NAME*" | tee -a $NPG/SPECS/$NAME-$VERSION.spec > /dev/null

[ "$MATE" == "enable" ] && echo "rm -r /usr/share/backgrounds/mate/$NAME
rm /usr/share/mate-background-properties/mate-$NAME.xml" | tee -a $NPG/SPECS/$NAME-$VERSION.spec > /dev/null

[ "$GNOME" == "enable" ] && echo "rm -r /usr/share/backgrounds/gnome/$NAME
rm /usr/share/mate-background-properties/gnome-$NAME.xml"  | tee -a $NPG/SPECS/$NAME-$VERSION.spec > /dev/null

[ "$DDE" == "enable" ] && echo "rm /usr/share/wallpapers/deepin/$NAME*" | tee -a $NPG/SPECS/$NAME-$VERSION.spec > /dev/null
}

create_rpm()
{
	cd $NPG/SPECS; rpmbuild -bb $NAME-$VERSION.spec
	cd $CWD; cp $NPG/RPMS/noarch/$NAME-wall-$VERSION-$RELEASE.$ARCH.rpm .
	chown -R 1000:users $NAME-wall-$VERSION-$RELEASE.$ARCH.rpm
}

[ "$1" == ""  ] && info_view
[ "$UID" != 0 ] && fail_root

PARM=$( echo $* | sed "s/ /&\n/g" | grep "\-\-"    )
LIST=$( echo $* | sed "s/ /&\n/g" | grep -v "\-\-" )

for OPTION in $PARM; do
	[ "$OPTION" == "--default"       ] && define_defaut
	[ "$OPTION" == "--enable-dde"    ] && DDE=enable
	[ "$OPTION" == "--enable-mate"   ] && MATE=enable
	[ "$OPTION" == "--enable-gnome"  ] && GNOME=enable
	[ "$OPTION" == "--disable-dde"   ] && DDE=disable
	[ "$OPTION" == "--disable-mate"  ] && MATE=disable
	[ "$OPTION" == "--disable-gnome" ] && GNOME=disable
done

for FILE in $LIST; do
	NAME=$( basename $FILE | cut -d '.' -f1 )
	NPG=~/rpmbuild
	PKG=/tmp/package-$NAME
	TMP=/tmp/$NAME
	mkdir -p $TMP $PKG/usr/share/{backgrounds/xfce,xfce4/backdrops,wallpapers} $NPG/SPECS
	[ "$DDE"   == "enable" ] && mkdir -p $PKG/usr/share/wallpapers/deepin
	[ "$MATE"  == "enable" ] && mkdir -p $PKG/usr/share/{backgrounds/mate/$NAME,mate-background-properties}
	[ "$GNOME" == "enable" ] && mkdir -p $PKG/usr/share/{backgrounds/gnome/$NAME,gnome-background-properties}
	cabextract -d $TMP $FILE
	mv $TMP/D*/* $PKG/usr/share/xfce4/backdrops/
	define_name
	chown -R root:root $PKG
	find -L $PKG \
		\( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
		-o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
	spec_gen
	create_rpm
	rm -rf $TMP $PKG $NPG
done
exit 0
